typography_spectrum: 0.9309891015291214
color:
  brandStrength: 0.7082991402130574
  lightness: 0.8641825148370117
  saturation: 0.38764717639423907
  rhythmicContrast: 0.2837808425538242
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.21020085248164833
name: physics
navigation:
  - name: My homepage
    url: 'http://jackmerrin.com'
    type: external
title: Jack Merrin
description: Wow I am on the grid
